### ISSUE TITLE
Undefined property Node::$roles when adding block field

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/blockreference#5] opened 2019-09-10 14:27 UTC
On a simple site I added a field and kept all the defaults. I get this error:

> Notice: Undefined property: Node::$roles in user_access() (line 474 of /home/qa/github/backdrop/backdrop/pr/2839/core/modules/user/user.module).

It is probably related to this error that I get at the same time:

> Warning: Invalid argument supplied for foreach() in user_role_permissions() (line 425 of /home/qa/github/backdrop/backdrop/pr/2839/core/modules/user/user.module).

**Comment by ghost** [comment] 2019-12-03 19:57
I think the issue's in `blockreference_autocomplete_access()`:

```php
if ($eid == 0) {
  ...
  if (function_exists($entity_type . '_access')) {
    $entity_access = call_user_func($entity_type . '_access', 'create', $entity_type, $entity_dummy);
  }
}
else {
  ...
  if (function_exists($entity_type . '_access')) {
    $entity_access = call_user_func($entity_type . '_access', 'update', $entity_type, $entity);
  }
}
```
I'm not sure about other `[ENTITY_TYPE]_access()` functions, but `node_access()` takes the following parameters:
- op
- node (or node_type when op == create)
- user account

The first `call_user_func()` doesn't need `$entity_dummy` (it should be the user account to check, not the node).
The second `call_user_func()` should have `$entity` as the 3rd parameter as the op is 'update', and then again should have the last parameter.

Making these changes on my local fixed the issue for me (though another issue popped up now)...

**Comment by ghost** [comment] 2019-12-03 20:05
Seems this might already be fixed in latest dev: https://github.com/backdrop-contrib/blockreference/commit/2ea2a3407dc53607fe3657a0443940613c5b7e1c

**Comment by yorkshire-pudding** [comment] 2022-12-08 12:22
Can't reproduce this. suspect this is fixed by the other issues.

**Closed as not planned by yorkshire-pudding** 2022-12-08 12:22 UTC
